### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by B0y1n4o4** [med0x2e/GadgetToJScript#8]
when i run message.exe it will pop messagebox，nothing happened when run wscript, cscript , mshta such command
```
C:\Users\Alice\Desktop\tools>GadgetToJScript.NET3.5.exe -c message.txt -d System.Windows.Forms.dll -w js -r
[+]: Generating the js payload
[+]: Compiling your .NET code located at:message.txt
[+]: Second stage gadget generation done.
[*]: Payload generation completed, check: test.js

C:\Users\Alice\Desktop\tools>cscript test.js
Microsoft (R) Windows Script Host Version 5.812
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\Alice\Desktop\tools>whoami
offensive\alice
```

with bypass mode, error
```
C:\Users\Alice\Desktop\tools>GadgetToJScript.NET3.5.exe -a message.exe -w js -r -b
[+]: Generating the js payload

Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Runtime.Serialization.SerializationInfo.SetType(Type type)
   at GadgetToJScript.TextFormattingRunPropertiesMarshal.GetObjectData(SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at GadgetToJScript._DisableTypeCheckGadgetGenerator.generateGadget(MemoryStream ms)
   at GadgetToJScript.Program.Main(String[] args)
```

systeminfo
```
C:\Users\Alice\Desktop\tools>systeminfo

Host Name:                 CLIENT1
OS Name:                   Microsoft Windows 10 Enterprise Evaluation
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:
Registered Organization:   Microsoft
Product ID:                00329-20000-00001-AA236
Original Install Date:     3/19/2019, 5:59:35 AM
System Boot Time:          7/12/2021, 7:26:56 PM
System Manufacturer:       VMware, Inc.
System Model:              VMware Virtual Platform
System Type:               x64-based PC
Processor(s):              2 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
                           [02]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              Phoenix Technologies LTD 6.00, 7/22/2020
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     2,047 MB
Available Physical Memory: 955 MB
Virtual Memory: Max Size:  4,479 MB
Virtual Memory: Available: 2,132 MB
Virtual Memory: In Use:    2,347 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    offensive.local
Logon Server:              \\DC
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB4601555
                           [02]: KB4465065
                           [03]: KB4470788
                           [04]: KB4480056
                           [05]: KB4486153
                           [06]: KB4503308
                           [07]: KB4580325
                           [08]: KB5003243
                           [09]: KB4489899
Network Card(s):           1 NIC(s) Installed.
                           [01]: Intel(R) PRO/1000 MT Network Connection
                                 Connection Name: Ethernet0
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.159.10
                                 [02]: fe80::2d18:c49d:84a1:ee9a
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

```

**Comment by B0y1n4o4** [comment]
I tried another win10 system B, it can work fine, and copy test.js to `Alice` Win10，it still work fine。
but in `Alice` win10 generate test.js，it not working in B and local
